apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: backupuser
  namespace: database
spec:
  name: backupuser
  mariaDbRef:
    name: mariadb-galera

  passwordSecretKeyRef:
    name: backup-password
    key: password

  host: "%"
  maxUserConnections: 5
  cleanupPolicy: Delete