apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: migration-user
  namespace: database
spec:
  name: migrationuser

  mariaDbRef:
    name: mariadb-galera

  passwordSecretKeyRef:
    name: migration-password
    key: password

  host: "%"

  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s