apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: backupuser-appdb
  namespace: database
spec:
  mariaDbRef:
    name: mariadb-galera

  privileges:
    - SELECT
    - SHOW VIEW
    - TRIGGER

  database: appdb
  table: "*"

  username: backupuser
  host: "%"

  grantOption: false
  cleanupPolicy: Delete